### PR TITLE
bblayers.conf: Add meta-multimedia OE layer

### PR DESCRIPTION
**Pull request by GordanM**
Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

### CODE REVIEW

**Review by zeenix — CHANGES_REQUESTED** [review]
Some info on what the layer is and what we are adding it, would be good.

**Review by DunderRoffe — APPROVED** [review]
Agree with @zeenix but otherwise fine

**Comment by GordanM** [comment]
@DunderRoffe and @zeenix fixed.

**Review by zeenix — APPROVED** [review]
:+1:

**Pull request merged**
